"""Added AddressHistoryModel

Revision ID: 589175e543da
Revises: 6bc20d4f218a
Create Date: 2024-09-09 10:51:40.463382

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '589175e543da'
down_revision: Union[str, None] = '6bc20d4f218a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('address_id', sa.Integer(), nullable=True),
        sa.Column('old_address', sa.String(), nullable=False),
        sa.Column('new_address', sa.String(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),  # Ensure not nullable
        sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_history_id'), 'address_history', ['id'], unique=False)

    # Adding the address_type column to the addresses table
    op.add_column('addresses', sa.Column('address_type', sa.String(), nullable=False, server_default="shipping"))  # Consider setting default

    # Correcting nullable and default values in the users table
    op.alter_column('users', 'language_code',
        existing_type=sa.VARCHAR(length=35),
        nullable=False,  # Keep this non-nullable
        existing_server_default=sa.text("'en'::character varying"))

    op.alter_column('users', 'is_active',
        existing_type=sa.BOOLEAN(),
        nullable=False,  # Keep non-nullable
        existing_server_default=sa.text('true'))

    op.alter_column('users', 'is_admin',
        existing_type=sa.BOOLEAN(),
        nullable=False,  # Keep non-nullable
        existing_server_default=sa.text('false'))

    op.alter_column('users', 'is_email_verified',
        existing_type=sa.BOOLEAN(),
        nullable=False,  # Keep non-nullable
        existing_server_default=sa.text('false'))

    op.alter_column('users', 'is_phone_verified',
        existing_type=sa.BOOLEAN(),
        nullable=False,  # Keep non-nullable
        existing_server_default=sa.text('false'))

    op.alter_column('users', 'two_factor_enabled',
        existing_type=sa.BOOLEAN(),
        nullable=False,  # Keep non-nullable
        existing_server_default=sa.text('false'))

    op.alter_column('users', 'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,  # Keep non-nullable
        existing_server_default=sa.text('now()'))

    op.alter_column('users', 'updated_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,  # Keep non-nullable
        existing_server_default=sa.text('now()'),
        onupdate=sa.func.now())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'))

    op.alter_column('users', 'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'))

    op.alter_column('users', 'two_factor_enabled',
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text('false'))

    op.alter_column('users', 'is_phone_verified',
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text('false'))

    op.alter_column('users', 'is_email_verified',
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text('false'))

    op.alter_column('users', 'is_admin',
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text('false'))

    op.alter_column('users', 'is_active',
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text('true'))

    op.alter_column('users', 'language_code',
        existing_type=sa.VARCHAR(length=35),
        nullable=False,
        existing_server_default=sa.text("'en'::character varying"))

    op.drop_column('addresses', 'address_type')
    op.drop_index(op.f('ix_address_history_id'), table_name='address_history')
    op.drop_table('address_history')
    # ### end Alembic commands ###
